### ISSUE TITLE
Arduino simulator page 😀 for the Arduino-Buzzer-Tone-Codes

### ISSUE THREAD

**Issue by matititam** [AbhishekGhosh/Arduino-Buzzer-Tone-Codes#4]
hi Abhishek

Good day!

Thank you for the wonderful library for the Arduino Buzzer application. 
I have created a permanent link on the Wokwi Arduino simulator.
https://wokwi.com/arduino/projects/309974695864697409

Kindly let me know, how can Wokwi Arduino simulator help to support people like you who create useful libraries?

It would be great for your library readers, if you can add this to the ReadMe page. I am sure, it will be received well. People can play with it before they adapt to their project!

Thank you
Matititam

**Comment by AbhishekGhosh** [comment]
@matititam Many thanks. It is a great tool. I have updated the README -- https://github.com/AbhishekGhosh/Arduino-Buzzer-Tone-Codes/blob/master/README.md

**Comment by matititam** [comment]
Dear Abhishek
Thanks a lot

Can you suggest any improvement points for the simulator? please reply at your own time

Thanks
Matititam

**Comment by AbhishekGhosh** [comment]
You are welcome! The UI needs improvement. Presently it does the job nicely but probably less attractive to the new users.

**Comment by matititam** [comment]
Hi Abhishek,

Thank you for the reply. Can you suggest a couple of changes you would like to see in the UI?

Thank you
Puneeth
